<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Projeto de PHP com POO e PDO">
    <title><?=$data['page_title']?><?=SITE_NAME?></title>
</head>
<body>
    <header>
        <img>
        <nav>
            <a href="<?=SITE?>/admin">Dashboard</a>
<?php if($data['session']->user_profile_id == 1) :?>
            <a href="<?=SITE?>/admin/user">Usuários </a>
<?php endif; ?>
            <a href="<?=SITE?>/logoff">Sair </a>
            <a href="<?=SITE?>">Visitar Site </a>
            Olá, <?=$data['session']->user_firstName?>
        </nav>
    </header>
