    
    <main>
        <h1>Sistema instalado com sucesso no servidor.</h1>
        <p>Para acessar a área administrativa <a href="<?=SITE?>/admin">clique aqui</a>.</p>
        <p>O acesso na área administrativa deve ser realizado utilizando o usuário e senha inicial:<p>
        <p>E-mail: admin@mvc.mvc<br>
        <p>Senha: admin</p>
        <br><br>
        <p>Para acessar a página principal, <a href="<?=SITE?>">clique aqui</a>.</p>
    </main>
    