

    <main>
        <h1>Criar Usuário</h1>
    <?php if(!empty($data['message'])):?>
        <?=implode('<br>', $data['message'])?>
    <?php endif;?>
        <form method="post">
            <input name="user_code_unique" type="text" placeholder="CPF (Somente número. Ex: 00011122233)" value="<?=old_value('user_code_unique')?>">
            <input name="user_firstName" type="text" placeholder="Primeiro Nome" value="<?=old_value('user_firstName')?>">
            <input name="user_lastName" type="text" placeholder="Sobrenome" value="<?=old_value('user_lastName')?>">
            <input name="user_email" type="email" placeholder="E-mail" value="<?=old_value('user_email')?>">
            <input name="user_password" type="password" placeholder="Senha">
            <button type="submit">Criar Conta</button>
        </form>
    </main>
    